### ISSUE TITLE
Bold, Italic fonts are not recognized

### ISSUE THREAD

**Issue by hassanzadeh** [danielsaidi/RichTextKit#155] opened 2024-03-04 14:08 UTC
Hey Guys,
I need to import a simple mark up text into this editor, my markup is very simple, it only has these HTML tags, <b>, <i>, <u>, <be>, I couldn't find an easy way to import so I wrote a simple script that turns those text spans enclosed by the tags into attributes (eg, Bold). The problem is that the converted NSAttributedString in my case has features like this:
`{
    NSFont = "\"Times-Italic 12.00 pt. P [] (0x107a09380) fobj=0x107a39f80, spc=3.00\"";
    NSKern = 0;
    NSParagraphStyle = "Alignment Natural, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode WordWrapping, Tabs (\n), DefaultTabInterval 36, Blocks (\n), Lists (\n), BaseWritingDirection LeftToRight, HyphenationFactor 0, TighteningForTruncation YES, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint ''";
    NSStrokeColor = "sRGB IEC61966-2.1 colorspace 0 0 0 1";
    NSStrokeWidth = 0;
}`

however, it looks like such font is not recognized by RichTextKit, not sure why. When I print the features generated by RichTextKit, it looks like this:
`{
    NSColor = "Catalog color: System textColor";
    NSFont = "\".SFNS-RegularItalic 16.00 pt. P [] (0x17ab7f300) fobj=0x17ab7f300, spc=4.20\"";
    NSKern = 0;
    NSParagraphStyle = "Alignment Natural, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode WordWrapping, Tabs (\n), DefaultTabInterval 36, Blocks (\n), Lists (\n), BaseWritingDirection LeftToRight, HyphenationFactor 0, TighteningForTruncation YES, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint ''";
    NSStrokeColor = "sRGB IEC61966-2.1 colorspace 0 0 0 1";
    NSStrokeWidth = 0;
}`

Why does RichTextKit not recognize the former? How can I import the attributed text so that it recognizes the bold and italic parts correctly?

thanks

**Comment by karlmira** [comment] 2024-03-04 14:18
Can confirm this. Up to 0.9.8 storing formatted text to core data was no problem. Since 0.9.9 reloaded data loses formatting of bold and italic. Although it can be set again, but this is ignored while being stored back to core data.

Process:

- Create new letter and add text
- Format text with bold and italic
- Store to core data and print to pdf -> no problem. Formatting is there
- Printing directly from core data to pdf -> no problem, formatting still there
- Loading from database -> formatting in RTE is gone
- Adding bold or italic to text is visible in editor, but is gone after storing back to core data
- Printing to pdf doesn't show any bold or italic formatting.

Amazingly, underlined is still working. Indent, too.

**Comment by DominikBucher12** [comment] 2024-03-04 14:46
Hey guys, this looks like issue of the font and configuration, however I am not familiar with the storing functionality, this is probably up to @danielsaidi to figure out, we can take a look together 😅

**Comment by danielsaidi** [comment] 2024-03-04 19:55
@hassanzadeh @karlmira @DominikBucher12 

I have created a new demo app in the main branch (will soon push) that uses a `DocumentGroup` instead of the current demo. That way, the document is saved, which makes it a LOT easier to detect when things go wrong.

With this new demo, I can confirm that text restoration is broken, but it only seems broken on macOS. When I apply fonts, text colors, bold, etc. in iOS, it seems to work.

@karlmira Do you mean that the restoration worked in 0.9.8, or that it stopped working in 0.9.8?

@DominikBucher12 This seems to be connected to `setupTheme` in `RichTextView_AppKit`. As soon as I disable `setupTheme()` the color and underline works again :D 

Here's that function for macOS (left) and iOS (right):

<img width="1051" alt="image" src="https://github.com/danielsaidi/RichTextKit/assets/429927/52d2fbb1-b56a-418a-9eb3-9b695f1e2b9c">

As you can see, the two differ in functionality. This is why we should aim to keep the duplicated code to a minimum and try to aim for a single implementation using protocols.

**Comment by danielsaidi** [comment] 2024-03-04 20:10
This is fixed in the `main` branch.

**Closed by danielsaidi** 2024-03-04 20:10 UTC
Labels: bug

**Comment by hassanzadeh** [comment] 2024-03-04 20:46
Hi @danielsaidi ,
Thanks for the quick turn around, but I'm still having observing similar behavior, I reinstalled the package, however, the following NSString is still showing as regular text:
`Bold{
    NSFont = "\"Times-Bold 12.00 pt. P [] (0x1079c9680) fobj=0x107909880, spc=3.00\"";
    NSKern = 0;
    NSParagraphStyle = "Alignment Natural, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode WordWrapping, Tabs (\n), DefaultTabInterval 36, Blocks (\n), Lists (\n), BaseWritingDirection LeftToRight, HyphenationFactor 0, TighteningForTruncation YES, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint ''";
    NSStrokeColor = "sRGB IEC61966-2.1 colorspace 0 0 0 1";
    NSStrokeWidth = 0;
}
Italic
{
    NSFont = "\"Times-Italic 12.00 pt. P [] (0x1079c9680) fobj=0x1079e7900, spc=3.00\"";
    NSKern = 0;
    NSParagraphStyle = "Alignment Natural, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode WordWrapping, Tabs (\n), DefaultTabInterval 36, Blocks (\n), Lists (\n), BaseWritingDirection LeftToRight, HyphenationFactor 0, TighteningForTruncation YES, HeaderLevel 0 LineBreakStrategy 0 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint ''";
    NSStrokeColor = "sRGB IEC61966-2.1 colorspace 0 0 0 1";
    NSStrokeWidth = 0;
}`

By the way, this is in a macOS app.
<img width="255" alt="image" src="https://github.com/danielsaidi/RichTextKit/assets/13952413/ed79fca8-dfbe-461a-ae3c-3634cd2c9d17">

**Comment by danielsaidi** [comment] 2024-03-04 21:08
Can you try the new demo app in the `main` branch?

**Comment by hassanzadeh** [comment] 2024-03-04 23:21
Thanks @danielsaidi  for the quick response,
You are right, when I install the package locally from your code it works, but when I install the package using SPM from the github link it install the old version, not sure if something is cached that is causing this or it's due to another issue.

**Comment by karlmira** [comment] 2024-03-05 03:36
Can't update, too. Looks like something went wrong on github. 
Flag for last update tells "failure" with a red x

**Comment by danielsaidi** [comment] 2024-03-05 06:59
@hassanzadeh Yes, this is a not yet released bug fix.

**Comment by karlmira** [comment] 2024-03-05 07:02
Here we go.

![Bildschirmfoto 2024-03-05 um 08 01 17](https://github.com/danielsaidi/RichTextKit/assets/111527454/66bf4587-02c6-441c-a945-021734a7c697)

**Comment by danielsaidi** [comment] 2024-03-05 07:08
This is a failure in the yet to be correctly configured test runner :)

I meant what error you get when you try to use the main branch?

**Comment by karlmira** [comment] 2024-03-05 12:44
Ok, with actual main branch everything works fine now.
Thanks for your quick help.

**Comment by danielsaidi** [comment] 2024-03-05 14:50
That's amazing to hear 🙌
